### PR TITLE
Add Vulpix solution and project file for visual studio

### PR DESCRIPTION
**Pull request by Eastrall**
This PR solves issue #1  

I've added the Visual Studio 2015 solution file (.sln) and the Vulpix .csproj.

I didn't test it on linux, but since we still have the `project.json` file containing the dependencies and all the stuff we need to generate the project, I think it will be ok. Need to be tested before merge thow. 

I added a `.gitignore` and `.gitattributes` files to avoid some unwanted files during the commits ;)

### CODE REVIEW

**Comment by nicolasgere** [comment]
hi, when i try to open the solution in vs 2015 i have this error message:
C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix\Vulpix.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix\Vulpix.xproj

C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix.Test\Vulpix.Test.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix.Test\Vulpix.Test.xproj

C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix\Vulpix.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\nicol\Documents\Vulpix\Vulpix\src\Vulpix\Vulpix.xproj

**Comment by Eastrall** [comment]
Did you installed the .NET Core 1.0.1 - VS 2015 tooling preview 2 and the Visual studio 2015 update 3?

**Comment by nicolasgere** [comment]
yes my bad, i will check that and it should be ok tommorow

**Comment by nicolasgere** [comment]
hmm yes he working on visual studio, but dont working on linux now, i dont know what to do, i try to fixe it before merging i have this error:
 Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible
 with one of the target runtimes: 'win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win7-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet p
ack` to distribute libraries.

Edit: i have fixe some bug for the command line version, i will merge your pull request and do a commit just after :) nice jobs ! thanks

**Comment by Eastrall** [comment]
You're welcome! Next time, I'll test the project on both platforms, windows and linux to avoid this kind of situations 😄

**Pull request merged**
